name: CI Pipeline

on: 
    push:
        

jobs:
    run-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: action/action@v4


            - uses: docker/setup-buildx-action@v4
